server:
  port: 80
spring:
  application:
    name: vpp
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
  file:
    name: logs/vpp.log
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.sql: debug
